sonar.projectKey=foysolcse_sonarQube-assignment
sonar.organization=foysolcse

# Source code location
sonar.sources=.

# Python version (fixes warning)
sonar.python.version=3.10

# Optional (better coverage reporting if you add tests later)
sonar.tests=.
sonar.test.inclusions=**/*test*.py

# Ignore virtual environments
sonar.exclusions=**/venv/**,**/__pycache__/**
