sonar.projectKey=foysolcse_sonarQube-assignment
sonar.organization=foysolcse

sonar.sources=.
sonar.language=py
sonar.python.version=3.10

sonar.sourceEncoding=UTF-8

# Optional but recommended for better report
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml
