sonar.projectKey=foysolcse_sonarQube-assignment
sonar.projectName=sonarQube-assignment

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.10
sonar.exclusions=**/venv/**,**/__pycache__/**
