name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          run: pip install pytest pytest-cov

      - name: Run Tests with Coverage
        run: pytest --cov=. --cov-report=xml

      - name: Install SonarScanner
        run: |
          npm install -g sonar-scanner

      - name: Run SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=foysolcse_sonarQube-assignment \
            -Dsonar.organization=foysolcse \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
